spring:
#  datasource:
#    url: jdbc:h2:mem:test_db
#    username: sai
#    password: password
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: false
#    database-platform: org.hibernate.dialect.H2Dialect