app:
  name: springboot-basic-auth

server:
  servlet:
    context-path: /app
    encoding:
      charset: UTF-8

spring:
  profiles.active: local
  application:
    name: ${app.name:springboot-basic-auth}
  main:
    banner-mode: off

# root level
logging:
  level:
    root: error
    com.abciloveu: debug
    org.springframework: error
    org.hibernate: error
  file:
    name: ${app.name}.log
    path: d:\\logs\applog\${app.name}

